swagger: "2.0"
info:
  description: "This is a example"
  version: "1.0.0"
  title: "Swagger Example"
basePath: "/v1"
host: localhost:8080
tags:
  - name: "User"
    description: "User Module"
schemes:
  - "http"
paths:
  /users:
    get:
      operationId: getUsers
      summary: 用户列表
      tags:
        - "User"
      parameters:
        - name: "age"
          in: query
          required: false
          type: string
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/User"


definitions:
  User:
    description: "用户信息"
    type: object
    properties:
      id:
        type: integer
        format: int64
        description: "用户id"
      name:
        type: string
        description: "用户名"
      create_time:
        type: integer
        format: int64
        description: "创建时间"
