# https://editor.swagger.io/
openapi: 3.0.0
info:
  description: "This is a example"
  version: "1.0.0"
  title: "Swagger Example"
servers:
  - url: "http://api.example.com/v1"
    description: "Optional server description, e.g. Main (production) server"
  - url: "http://staging-api.example.com"
    description: "Optional server description, e.g. Internal staging server for testing"

tags:
  - name: "User"
    description: "User Module"

paths:
  /session:
    post:
      operationId: login
      summary: 登录
      tags:
        - "User"
      requestBody:
        required: true
        description: "登录信息"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SessionInput"
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SessionToken"
  /users:
    get:
      operationId: getUsers
      summary: 用户列表
      tags:
        - "User"
      parameters:
        - name: "age"
          in: query
          required: false
          schema:
            type: string
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"

components:
  schemas:
    User:
      description: "用户信息"
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: "用户id"
        name:
          type: string
          description: "用户名"
        create_time:
          type: integer
          format: int64
          description: "创建时间"
    SessionToken:
      description: "登录后的token"
      type: object
      properties:
        token:
          type: string
          description: "token信息"
    SessionInput:
      description: "登录账号"
      type: object
      properties:
        user_name:
          type: string
          minLength: 1
          maxLength: 20
        password:
          type: string
          minLength: 1
          maxLength: 20
  securitySchemes:
    user_auth:
      type: http
      scheme: bearer